### ISSUE TITLE
transaction fail during `dapple test`

### ISSUE THREAD

**Issue by nmushegian** [NexusDevelopment/dapple#30]
```
(makerdao)[nikolai:~/maker-project/ens]$ dapple test                                                                                                                                                                               (master✱)
No handlers could be found for logger "eth.pow"
Testing ENSTest
  testCuratedNameregGet
Traceback (most recent call last):
  File "/Users/nikolai/.virtualenvs/makerdao/bin/dapple", line 9, in <module>
    load_entry_point('dapple==0.0.1a0', 'console_scripts', 'dapple')()
  File "/Users/nikolai/.virtualenvs/makerdao/lib/python2.7/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/nikolai/.virtualenvs/makerdao/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/Users/nikolai/.virtualenvs/makerdao/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/Users/nikolai/.virtualenvs/makerdao/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.macosx-10.10-intel/egg/dapple/__main__.py", line 11, in <module>
  File "/Users/nikolai/.virtualenvs/makerdao/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/Users/nikolai/.virtualenvs/makerdao/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/Users/nikolai/.virtualenvs/makerdao/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/nikolai/.virtualenvs/makerdao/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/nikolai/.virtualenvs/makerdao/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "build/bdist.macosx-10.10-intel/egg/dapple_core/__init__.py", line 494, in test
  File "/Users/nikolai/.virtualenvs/makerdao/lib/python2.7/site-packages/ethertdd/__init__.py", line 53, in kall
    'value', 'output'))
  File "/Users/nikolai/.virtualenvs/makerdao/lib/python2.7/site-packages/ethereum/tester.py", line 201, in _send
    raise TransactionFailed()
ethereum.tester.TransactionFailed
```

**Comment by ryepdx** [comment]
Checked this again in the Docker and it looks like it's working:

```
(nexus)root@e271e272afe5:~/devenv/ENS# pydapple test
No handlers could be found for logger "eth.pow"
Testing ENSTest
  testCuratedNameregGet
    LOG: Setting 'key' on node #2 to 'value'
    Used 5352 gas
  testCuratedNameregSet
    LOG: Setting 'key' on node #2 to 'value'
    Used 6361 gas
  testResolve
    LOG: Setting 'key' on node #2 to 'value'
    LOG:  
    LOG: 1 
    Fail!
  testRootNodeConfigured
    LOG: Setting 'key' on node #2 to 'value'
  testRootNodeController
    LOG: Setting 'key' on node #2 to 'value'
    Fail!
Testing ENSControllerDBTest
  testEverything
Testing StdRegTest
  testBasicRegistry
    LOG: assertTrue was false 
    LOG: Not equal! 
    LOG:  
    LOG: value 
    Fail!
(nexus)root@e271e272afe5:~/devenv/ENS# 
```
