### ISSUE TITLE
Unable to run latest dapple

### ISSUE THREAD

**Issue by drupalnomad** [NexusDevelopment/dapple#43]
```
/usr/lib/node_modules/dapple/lib/workspace.js:21
module.exports = class Workspace {
                 ^^^^^
SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/dapple/cmd/main.js:5:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by nmushegian** [comment]
How are you running it? What's your node --version?

**Comment by nmushegian** [comment]
actually it looks like your dapple is just out of date. `devenv` submodules are often not updated...
