### ISSUE TITLE
excessive test error output

### ISSUE THREAD

**Issue by nmushegian** [NexusDevelopment/dapple#59]
When `dapple test` emits a build error it is a bit much:

```
[nikolai:~/devenv/dappsys]$ dapple test                                                                                                            (master✱)
Testing...
Using local solc installation...
_b808a79698a9b8d6895e865d5dec7832670e167c5756db6e759ce55ee6f9b269.sol:30:9: Error: Expected token Semicolon
        assertFalse( t.transferFrom(bob, self, 1) );
        ^
/Users/nikolai/devenv/dapple/node_modules/solc/bin/soljson-latest.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileSync"](f

Error: Command failed: solc -o - --combined-json abi,bin,interface _0e7651d36fab71690040c9d5de72fe671fed5af6b8fceb77c7ba2d40cf9aafd0.sol _445d9c43b67e37734b3fa54a3528ebd7af75c5ca2f58f9d3637beb68993f100a.sol _25f1e8fafd9c4905611b2e5e759d4457fc544f4af3ea91ea7eebad75143af8f7.sol _e7d9842fd028e7425e024f58e9002a8d82b549bf121aed3eb47be6eb937546cd.sol _b563e0077003af2ede798715d41307b6f27b88a078f67bd142b17cc3459bf5f0.sol _fcfd119cc6ee85730870b00396f38db771798ba6638cb730f1e245a807a99c8e.sol _39acb140924d1e4463d794d2ca1365f84d358026f369e376e8d528e2c9697061.sol _27c8590c6c7eaeee572d5f1d4e8a01675f469f7ef5b2936be1be5f6e5f832eb9.sol _574b8f3e43b1844e442dfc169c287437b2293e4c3cd546a733af71d76cdbc3ed.sol _7570c66cb2a4431cc3c3f761402aa73d177d0ec3fb34fe7c8dd6e6f21b24ef64.sol _c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470.sol _632ccef2bc2191dfeab57df193b0b8405976fae20cb2afef08e29285b3be6f26.sol _ac0a349729e3a8f0a19533c0cba38f1b00a8eada10ca65020818122ee4c247c0.sol _5b5520af27b82c1c06fd265af80fe7b50e68f342a380e610b724ad338e044ccf.sol _ecf575f1656c23b160768d409a882a5115a2abc122e0d11e858ee0b713fa1447.sol _bbefd701cc4d2ba5fccc681e3fad8eed60dd57ee35a73977a75eb5dbd19eda22.sol _0b4b74e02af60cf0f72f23e7fc84c38d980c3a8c1f7903058265acf1b0626711.sol _d1cbebf6f0303bc8c586f2e7d746641e21e1f412e55b4aac95170d718adc286a.sol _b7109fc099c93e70adb790483c0e191d75ef689df2e3eef50dea01ac25add6b3.sol _02aa44cbe600160256e5e5a59948ecbefba554bfe630e741df96df5623e0d302.sol _e5b559a11138df60e4ac5f082613946c118824ed4e083135fe2e377b8685ad5d.sol _2fce2b7a65c313cc73c4be2dd31ef13628587066e64e9b5adc2aebd067be5a96.sol _d7889cca302ecbaf847095d9a8d6255bdb759614e836049d0886197b22341bd3.sol _7d038c773c083d6b0b4f23ca84825ddd528bec31b0dbfe025f3e861121397b14.sol _307ff7e5f8c37d941a0392a805fff33f5f1a4b8afb4fdbb3ba226b78985fd00e.sol _b003af82fed413abdfd9a4979d98c877b6854875363cb9f74bd08cbf182395ac.sol _c3f7dedff685db95d20db267a5f627bc52d0bb3f2bdef0ec9b66fa37428b862b.sol _00e28e241a47dc15a3331b1a9fea91e1b8e25f154df600f8b9866a8edc88322d.sol _dca36c003e7f54365159d1de79853d26284726bee2e9d954f80555cf23d11bce.sol _a8f84a5d1f37047759545c924862d856377743981e2f453ed0fa86e1bc232212.sol _731d02e0d953f0229cf98b8576054c0d186bd82e729e273d59b58d1c9afe5655.sol _4d5ad5e29fd61425b2c9c1a5dd10e724fa8d827465637c6476cb58a440ac229b.sol _e7ae51985df4a8c0d4ad3cf06de9a4150761175bfafae21ac2c0a66ee094fc45.sol _8e424b62c347dbf7b3b12d59c6c9f62b866253c05e4b5a4320f59d0bdbce6d8a.sol _d5bdfd742dab919aaea7b42f240221adc54cd010b6be0fc1a616d241d81ee9e2.sol _23222f6940c2d21ebdd5cf00254ce70e35d18c4134b98659c95cc20a3872388d.sol _7f1f3102e32cbca7bd9439ce74cca169315b62d63e5275e19b227b14112b4aa4.sol _f809b572cfa54b1e0e4c31bd492f6577f862007994b857222f93b8f2fbf73ec4.sol _b808a79698a9b8d6895e865d5dec7832670e167c5756db6e759ce55ee6f9b269.sol _59676097b1165e387f9fb863fd19c6588c4a2dbf794271bec6e309ad31dc8777.sol _c49b3b0d54d4cf127f662d9d5fafea154c0603e5837bb2d210f752433ff08549.sol _e9d5714a9f5d36d96f7ad560b14cb5e0a2b0a150b4051a70b986b74163b1507b.sol _3f3c8ee65e5e97d9719bcebb1dc16f092af6640192d9fbec7ecad54cc1d426f1.sol _b280bf1c87d442fe49a7786e86bf217c4cc2b41b5ae0f1d569a7bdd9f968d987.sol
_b808a79698a9b8d6895e865d5dec7832670e167c5756db6e759ce55ee6f9b269.sol:30:9: Error: Expected token Semicolon
        assertFalse( t.transferFrom(bob, self, 1) );
        ^

    at checkExecSyncError (child_process.js:441:13)
    at Object.execSync (child_process.js:481:13)
    at Function.compile (/Users/nikolai/devenv/dapple/lib/native_compiler.js:29:47)
    at Function.buildSources (/Users/nikolai/devenv/dapple/lib/build.js:45:33)
    at DestroyableTransform._flush (/Users/nikolai/devenv/dapple/lib/streams/build.js:19:32)
    at DestroyableTransform.<anonymous> (/Users/nikolai/devenv/dapple/node_modules/readable-stream/lib/_stream_transform.js:123:12)
    at DestroyableTransform.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at DestroyableTransform.emit (events.js:166:7)
    at prefinish (/Users/nikolai/devenv/dapple/node_modules/readable-stream/lib/_stream_writable.js:501:12)
    at finishMaybe (/Users/nikolai/devenv/dapple/node_modules/readable-stream/lib/_stream_writable.js:509:7)
```

**Comment by nmushegian** [comment]
weird GH bug duplicate
