### ISSUE TITLE
dependencies still not linking properly

### ISSUE THREAD

**Issue by nmushegian** [NexusDevelopment/dapple#65]
```
[nikolai:~/maker-project/maker-core]$ dapple build                                                           (master✱)
Building...
/Users/nikolai/devenv/dapple/lib/workspace.js:103
        for (let glob of this.dappfile.ignore) {
                                      ^

TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at Workspace.getIgnoreGlobs (/Users/nikolai/devenv/dapple/lib/workspace.js:103:39)
    at Object.<anonymous> (/Users/nikolai/devenv/dapple/cmd/main.js:89:31)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
```

**Comment by ryepdx** [comment]
The error you're seeing was owed to the Workspace class not handling missing dappfile keys properly. Should be working now. Please confirm.

**Comment by nmushegian** [comment]
nope
```
Error: gulp-match: empty glob array
    at module.exports (/Users/nikolai/devenv/dapple/node_modules/gulp-match/index.js:36:10)
    at DestroyableTransform._transform (/Users/nikolai/devenv/dapple/node_modules/gulp-ignore/index.js:17:8)
    at DestroyableTransform.Transform._read (/Users/nikolai/devenv/dapple/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (/Users/nikolai/devenv/dapple/node_modules/readable-stream/lib/_stream_transform.js:160:12)
    at doWrite (/Users/nikolai/devenv/dapple/node_modules/readable-stream/lib/_stream_writable.js:335:12)
    at writeOrBuffer (/Users/nikolai/devenv/dapple/node_modules/readable-stream/lib/_stream_writable.js:321:5)
    at DestroyableTransform.Writable.write (/Users/nikolai/devenv/dapple/node_modules/readable-stream/lib/_stream_writable.js:248:11)
    at StreamFilter.ondata (/Users/nikolai/devenv/dapple/node_modules/readable-stream/lib/_stream_readable.js:583:20)
    at emitOne (events.js:77:13)
    at StreamFilter.emit (events.js:169:7)
```

**Comment by julian1** [comment]
The gulp-match exception is fixed by https://github.com/NexusDevelopment/dapple/pull/67

**Comment by julian1** [comment]
Err. this is better https://github.com/NexusDevelopment/dapple/pull/68

**Comment by ryepdx** [comment]
@nmushegian Merged in @julian1's fix. How's it working for you now? If it's still broken, is there any way I can get a copy of the data you're running it on? Would save us both time.

**Comment by nmushegian** [comment]
it worked, thanks
