### ISSUE TITLE
bool `HexTranslator` is not defined

### ISSUE THREAD

**Issue by nmushegian** [NexusDevelopment/dapple#72]
```
/Users/nikolai/devenv/dapple/node_modules/solc/bin/soljson-latest.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileSync"](f

ReferenceError: that is not defined
    at Object.hexTranslators.bool [as val] (/Users/nikolai/devenv/dapple/lib/logtranslator.js:10:30)
    at /Users/nikolai/devenv/dapple/lib/logtranslator.js:54:48
    at /Users/nikolai/devenv/dapple/node_modules/lodash/index.js:3395:24
    at /Users/nikolai/devenv/dapple/node_modules/lodash/index.js:3073:15
    at baseForOwn (/Users/nikolai/devenv/dapple/node_modules/lodash/index.js:2046:14)
    at Function.mapValues (/Users/nikolai/devenv/dapple/node_modules/lodash/index.js:3394:9)
    at LogTranslator.translate (/Users/nikolai/devenv/dapple/lib/logtranslator.js:53:26)
    at arrayMap (/Users/nikolai/devenv/dapple/node_modules/lodash/index.js:1406:25)
    at Function.map (/Users/nikolai/devenv/dapple/node_modules/lodash/index.js:6710:14)
    at LogTranslator.translateAll (/Users/nikolai/devenv/dapple/lib/logtranslator.js:62:23)
```

**Comment by ryepdx** [comment]
Resolved with #84.
