### ISSUE TITLE
"Test class definition has no bytecode"

### ISSUE THREAD

**Issue by nmushegian** [NexusDevelopment/dapple#80]
try building this:   https://github.com/NexusDevelopment/dappsys/releases/tag/0.2-audit-part2
```
/Users/nikolai/devenv/dapple/node_modules/solc/bin/soljson-latest.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileSync"](f

Error: Test class definition has no bytecode
    at new Contract (/Users/nikolai/devenv/dapple/lib/contract.js:8:19)
    at DestroyableTransform._transform (/Users/nikolai/devenv/dapple/lib/streams/test.js:42:32)
    at DestroyableTransform.Transform._read (/Users/nikolai/devenv/dapple/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (/Users/nikolai/devenv/dapple/node_modules/readable-stream/lib/_stream_transform.js:160:12)
    at doWrite (/Users/nikolai/devenv/dapple/node_modules/readable-stream/lib/_stream_writable.js:335:12)
    at writeOrBuffer (/Users/nikolai/devenv/dapple/node_modules/readable-stream/lib/_stream_writable.js:321:5)
    at DestroyableTransform.Writable.write (/Users/nikolai/devenv/dapple/node_modules/readable-stream/lib/_stream_writable.js:248:11)
    at Stream.method [as write] (/Users/nikolai/devenv/dapple/node_modules/duplexer/index.js:47:39)
    at DestroyableTransform.ondata (/Users/nikolai/devenv/dapple/node_modules/readable-stream/lib/_stream_readable.js:583:20)
```

**Comment by ryepdx** [comment]
Just pushed a fix. Please confirm whether it resolves this issue for you.

**Comment by nmushegian** [comment]
yep
